<?php
session_start();
if($_SESSION["eid"]==1)
{
?>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      
    <style>
      .wrapper{
          width:600px;
          margin:0 auto;
         
      }
     .warning{
       color:red;
     }
    </style>
  </head>
  <body>
  <div class="wrapper">
  <div class="container-fluid mt-2">
  <div class="row">
  <div class="col-md-12">
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post" enctype="multipart/form-data">
      <fieldset>
      <legend class="text-center text-muted font-weight-bold"> AJOUT EMPLOYER </legend>
      <hr>
      <div class="card bg-light" style="padding:18px;border-radius: 25px;">
      
        <div class="form-group">
          <label class="font-weight-bold" for="name"> Name</label>
          <input type="text" class="form-control" name="name"  value="<?=$name ?>" required>
          <span class="warning"><?=$name_er; ?></span>
        </div>

        <div class="form-group">
          <label class="font-weight-bold" for="phone"> Phone</label>
          <input type="Number" class="form-control" name="phone" value="<?=$phone ?>" required>
        </div>

        <div class="form-group">
          <label class="font-weight-bold" for="email"> Email</label>
          <input type="email" class="form-control" name="email" value="<?=$email ?>"  required>
          <span class="warning"><?=$email_er; ?></span>
        </div>
          
        <div class="form-group">
          <label class="font-weight-bold" for="pass"> Password</label>
          <input type="password" class="form-control" name="pass" required>
          <span class="warning"><?=$pass_er; ?></span>
        </div>

        <div class="form-group">
          <label class="font-weight-bold" for="repass">Repeat Password</label>
          <input type="password" class="form-control" name="repass" required>
          <span class="warning"><?=$cpass_er; ?></span>
        </div>
        
        <div class="form-group">
        <div class="custom-file">
    <input type="file" class="custom-file-input" name="img" accept=".png, .jpg, .jpeg" >
    <label class="custom-file-label" >Choose file</label>
    <br>
    <span class="warning"><?=$im_er; ?></span>
  </div>
        </div>
        
        <div class="form-group" style="margin:auto;">
         <button class="btn btn-success" name="submit">Ajout</button>
          <a href="listemp.php"><input type="button" class="btn btn-secondary" value="cancel">   </a>
        </div>

      </fieldset>
    
    </form>
</div>
  </div>
  </div>    
  </div>
  </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" ></script>
  </body>
</html>
    <?php } else header('Location:listemp.php');?>